"""scripts/tracer_accuracy_harness.py -- synthetic accuracy validation for
the backward-tracer source-direction estimate.

Question this answers: does `run_adjoint_tracer()`'s `confidence` score
actually track BEARING ERROR -- i.e. is a "High" estimate more likely to
point at the real source than a "Moderate" one? The real deployment has
no source at a known location to check against, so this uses the same
technique as the SourceInversion recovery proof (tests/attribution/
test_inverse.py): ground truth generated by the REAL forward `Simulator`,
independent of the code under test.

What the harness does, per synthetic source placement:
  1. FORWARD (ground truth): a known point source at a known bearing/
     distance from the real NEL-001 receptor, run through the real
     `ctm.simulator.Simulator` driven by the real Nellore wind archive
     (`met.ingest_real_met`), recording the receptor's concentration at
     every archive hour.
  2. DETECTION: an hour counts as "the receptor saw this source" when the
     source's receptor concentration is >= `detect_frac` x its own
     monthly maximum. The worker's real trigger (Holt-Winters spike check
     in backend/lib/forecast.js) runs on total AQI in Node and is NOT
     reproduced here -- this relative-signal criterion is a disclosed
     stand-in, and results are reported at several `detect_frac` values.
  3. BACKWARD (code under test): the UNMODIFIED `run_adjoint_tracer()`
     from scripts/source_direction_worker.py, with the real
     `live_deployment` city and the worker's own defaults, for each
     detected hour. Bearing error = circular distance between its bearing
     and the true receptor->source bearing.

Important structural fact this harness makes explicit: the tracer never
sees concentrations. Its bearing/confidence for an hour depend only on
wind + receptor, so they are identical for every source placement. A
source only changes WHICH hours get evaluated.

Known optimism (disclosed, not hidden): this is an identical-twin
experiment -- forward and backward models use the same single-station,
spatially uniform wind, with no met error, no background variability,
and one isolated source. Real-world accuracy can only be worse than this.

Grid convention (ctm/grid.py): i-axis east (x), j-axis north (y);
bearings are compass degrees FROM the receptor TO the source, the same
convention `run_adjoint_tracer()` reports.
"""
from __future__ import annotations

import argparse
import copy
import json
import sys
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # allow running as a plain script
sys.path.insert(0, str(Path(__file__).resolve().parent))

import source_direction_worker as worker  # noqa: E402  (the code under test, imported unmodified)
from cities.loader import CityConfig, load_city  # noqa: E402
from ctm.grid import CTMGrid  # noqa: E402
from ctm.simulator import Simulator  # noqa: E402
from met.ingest_real_met import load_real_met_series  # noqa: E402
from met.weather_station import StationObservation  # noqa: E402

CITY_DIR = Path(__file__).resolve().parents[1] / "cities"
HARNESS_PROFILE = "harness_flat"
INCONCLUSIVE_CONFIDENCE = 0.1  # frontend/src/lib/sourceDirection.js
# confidenceWord() in frontend/src/components/SourceDirectionPanel.jsx,
# plus the "hidden" band isInconclusive() suppresses entirely.
BANDS = {
    "High": lambda c: c > 0.6,
    "Moderate": lambda c: (c > 0.3) & (c <= 0.6),
    "Uncertain": lambda c: (c > INCONCLUSIVE_CONFIDENCE) & (c <= 0.3),
    "hidden": lambda c: c <= INCONCLUSIVE_CONFIDENCE,
}


@dataclass(frozen=True)
class Placement:
    name: str
    i: int
    j: int
    true_bearing_deg: float
    distance_m: float


def bearing_error_deg(estimated: float, true: float) -> float:
    """Smallest angle between two compass bearings, in [0, 180]."""
    d = abs((estimated - true) % 360.0)
    return min(d, 360.0 - d)


def make_placements(grid: CTMGrid, ri: int, rj: int, bearings_deg, distances_m) -> list[Placement]:
    """Snap each requested bearing/distance to the nearest grid cell, then
    report the TRUE bearing/distance of that cell (not the requested one),
    so snapping never shows up as tracer error."""
    out = []
    for d in distances_m:
        for b in bearings_deg:
            i = ri + int(round(d * np.sin(np.radians(b)) / grid.dx))
            j = rj + int(round(d * np.cos(np.radians(b)) / grid.dy))
            if not (0 <= i < grid.nx and 0 <= j < grid.ny):
                raise ValueError(f"placement {b} deg / {d} m falls outside the domain")
            ex, ny_ = (i - ri) * grid.dx, (j - rj) * grid.dy
            out.append(Placement(
                name=f"src_b{int(round(b)):03d}_d{int(d)}", i=i, j=j,
                true_bearing_deg=float(np.degrees(np.arctan2(ex, ny_)) % 360.0),
                distance_m=float(np.hypot(ex, ny_)),
            ))
    return out


def build_forward_city(base_city_name: str, placements: list[Placement], v_dep_m_s: float, out_dir: Path) -> CityConfig:
    """Ground-truth city: the base city's real domain/UTC offset/dt/wind
    lookback, but one tracer species per placement (so every placement
    runs in ONE Simulator pass -- the model is linear and species never
    interact), each emitted only by its own point source, zero background,
    flat profile. No sensors (the forward run is never assimilated)."""
    raw = json.loads((CITY_DIR / f"{base_city_name}.json").read_text(encoding="utf-8"))
    grid = CTMGrid(load_city(base_city_name))
    raw = copy.deepcopy(raw)
    raw["city_name"] = f"{raw['city_name']}_tracer_accuracy_harness"
    raw["species"] = {p.name: {"unit": "ug_m3", "v_dep_m_s": v_dep_m_s, "background_conc": 0.0} for p in placements}
    raw["diurnal_profiles"] = {HARNESS_PROFILE: [1.0] * 24}
    raw["emission_sources"] = []
    for p in placements:
        lat, lon = grid.cell_to_latlon(p.i, p.j)
        raw["emission_sources"].append({
            "name": p.name, "kind": "point", "profile": HARNESS_PROFILE,
            "rates": {p.name: 1.0}, "lat": float(lat), "lon": float(lon),
        })
    raw["sensors"] = []
    path = out_dir / "tracer_accuracy_forward_city.json"
    path.write_text(json.dumps(raw), encoding="utf-8")
    city = load_city(path)
    # Guard: each source must land in exactly the cell it was placed in.
    fgrid = CTMGrid(city)
    for p, src in zip(placements, city.emission_sources):
        if fgrid.latlon_to_cell(src.lat, src.lon) != (p.i, p.j):
            raise AssertionError(f"{p.name} did not round-trip to cell ({p.i},{p.j})")
    return city


def forward_receptor_series(
    city: CityConfig, series: list[tuple[datetime, StationObservation]], ri: int, rj: int,
) -> tuple[list[datetime], dict[str, np.ndarray]]:
    """Runs the real Simulator over the whole wind series. Each hourly
    observation drives the steps from its timestamp to the next hour
    (piecewise-constant wind); the receptor value recorded after those
    steps is the concentration at ts + 1h. Returns (times, {species: values})."""
    steps_per_hour = int(round(3600.0 / city.dt_seconds))
    t0 = series[0][0]
    sim = Simulator(city, hour_utc0=t0.hour + t0.minute / 60.0)
    for sp in sim.grid.species:
        sim.grid.set_field(sp, np.zeros((sim.grid.nx, sim.grid.ny), dtype=np.float32))
    times, values = [], {sp: [] for sp in sim.grid.species}
    for idx, (ts, obs) in enumerate(series):
        if idx + 1 < len(series) and (series[idx + 1][0] - ts).total_seconds() != 3600:
            raise ValueError(f"wind series is not hourly-contiguous at {ts}")
        for _ in range(steps_per_hour):
            sim.step([obs])
        times.append(series[idx + 1][0] if idx + 1 < len(series) else None)
        for sp in sim.grid.species:
            values[sp].append(float(sim.grid.get_field(sp)[ri, rj]))
    keep = [k for k, t in enumerate(times) if t is not None]
    return [times[k] for k in keep], {sp: np.array(v)[keep] for sp, v in values.items()}


def run_tracer_per_hour(tracer_city: CityConfig, rlat: float, rlon: float, times, wind_loader) -> dict:
    """The code under test, called exactly as the worker calls it."""
    out = {}
    for ts in times:
        win = wind_loader(ts, tracer_city.wind_history_hours)
        out[ts] = worker.run_adjoint_tracer(tracer_city, rlat, rlon, win)
    return out


def evaluate(placements, times, receptor_series, tracer_by_hour, detect_frac: float,
             min_peak_frac_of_global: float = 1e-3) -> list[dict]:
    """One row per (placement, detected hour). A placement whose own peak
    is below `min_peak_frac_of_global` x the strongest placement's peak
    (all sources have the same unit rate) never really reached the
    receptor -- e.g. a source only ever downwind, seen through a sliver of
    numerical diffusion -- and is skipped rather than letting the
    per-source relative threshold promote that noise to a "detection"."""
    global_peak = max(float(receptor_series[p.name].max()) for p in placements)
    rows = []
    for p in placements:
        c = receptor_series[p.name]
        peak = float(c.max())
        if peak <= 0.0 or peak < min_peak_frac_of_global * global_peak:
            continue
        for k, ts in enumerate(times):
            if c[k] < detect_frac * peak:
                continue
            tr = tracer_by_hour.get(ts)
            if tr is None or tr["bearing_deg"] is None:
                continue
            rows.append({
                "source": p.name, "ts": ts.isoformat(), "true_bearing_deg": p.true_bearing_deg,
                "true_distance_m": p.distance_m, "signal_frac": float(c[k] / peak),
                "tier": tr["estimate_tier"], "confidence": float(tr["confidence"]),
                "bearing_deg": float(tr["bearing_deg"]),
                "bearing_error_deg": bearing_error_deg(tr["bearing_deg"], p.true_bearing_deg),
            })
    return rows


def _spearman(x, y) -> float:
    from scipy.stats import spearmanr
    if len(x) < 3 or np.all(np.asarray(x) == x[0]) or np.all(np.asarray(y) == y[0]):
        return float("nan")
    return float(spearmanr(x, y).statistic)


def summarize(rows: list[dict], n_boot: int = 1000, seed: int = 0) -> dict:
    """Band table + Spearman(confidence, bearing_error) per tier and pooled.
    The CI is an HOUR-CLUSTERED bootstrap: one tracer run per hour is shared
    by every source detected that hour, so rows are not independent."""
    rng = np.random.default_rng(seed)
    out = {}
    for tier in ("pooled", "interior", "boundary_sector_fallback"):
        rs = [r for r in rows if tier == "pooled" or r["tier"] == tier]
        if not rs:
            continue
        conf = np.array([r["confidence"] for r in rs]); err = np.array([r["bearing_error_deg"] for r in rs])
        hours = np.array([r["ts"] for r in rs]); uh = np.unique(hours)
        idx_by_hour = {h: np.flatnonzero(hours == h) for h in uh}
        boots = []
        for _ in range(n_boot):
            pick = np.concatenate([idx_by_hour[h] for h in rng.choice(uh, size=len(uh), replace=True)])
            boots.append(_spearman(conf[pick], err[pick]))
        boots = np.array([b for b in boots if np.isfinite(b)])
        bands = {}
        for name, in_band in BANDS.items():
            m = in_band(conf)
            e = err[m]
            bands[name] = {
                "n": int(m.sum()), "hours": int(len(np.unique(hours[m]))),
                "median_err": float(np.median(e)) if e.size else None,
                "p_within_45": float(np.mean(e <= 45)) if e.size else None,
                "p_within_90": float(np.mean(e <= 90)) if e.size else None,
            }
        out[tier] = {
            "n": len(rs), "hours": int(len(uh)), "median_err": float(np.median(err)),
            "p_within_45": float(np.mean(err <= 45)), "p_within_90": float(np.mean(err <= 90)),
            "spearman_conf_vs_err": _spearman(conf, err),
            "spearman_ci95": [float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))] if boots.size else None,
            "bands": bands,
        }
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--city", default="live_deployment")
    ap.add_argument("--receptor", default="NEL-001")
    ap.add_argument("--bearings", default="0:360:22.5", help="start:stop:step degrees")
    ap.add_argument("--distances", default="2000,5000,9000")
    ap.add_argument("--detect-fracs", default="0.05,0.01,0.2", help="first value is the headline result")
    ap.add_argument("--out", default=None, help="write rows + summary JSON here")
    args = ap.parse_args()

    tracer_city = load_city(args.city)
    rec = next(s for s in tracer_city.sensors if s.id == args.receptor)
    grid = CTMGrid(tracer_city)
    ri, rj = grid.latlon_to_cell(rec.lat, rec.lon)
    b0, b1, bs = (float(x) for x in args.bearings.split(":"))
    placements = make_placements(grid, ri, rj, np.arange(b0, b1, bs), [float(d) for d in args.distances.split(",")])

    series, _ = load_real_met_series(
        [worker.NELLORE_MET_CSV], station_id=worker.NELLORE_STATION_ID,
        lat=worker.NELLORE_STATION_LAT, lon=worker.NELLORE_STATION_LON,
    )
    with tempfile.TemporaryDirectory() as td:
        fwd_city = build_forward_city(args.city, placements, tracer_city.species["pm25"].v_dep_m_s, Path(td))
    times, rseries = forward_receptor_series(fwd_city, series, ri, rj)
    tracer_by_hour = run_tracer_per_hour(tracer_city, rec.lat, rec.lon, times, worker.load_nellore_wind_history)

    report = {"receptor": [rec.lat, rec.lon, ri, rj], "n_placements": len(placements), "n_hours": len(times), "by_detect_frac": {}}
    for f in (float(x) for x in args.detect_fracs.split(",")):
        rows = evaluate(placements, times, rseries, tracer_by_hour, f)
        report["by_detect_frac"][str(f)] = {"summary": summarize(rows), "rows": rows}
    print(json.dumps({k: {"summary": v["summary"]} for k, v in report["by_detect_frac"].items()}, indent=1))
    if args.out:
        Path(args.out).write_text(json.dumps(report, default=str), encoding="utf-8")


if __name__ == "__main__":
    main()
